version: "3"

services:
  app:
    runtime: nvidia
    image: bwidemo:latest
    container_name: bwiros
    build: .
    environment:
      # these env variables enable use of the display and GPU
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes: # volumes allow persistent data on the host
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /usr/local/cuda:/usr/local/cuda
      # Uncomment the line below to persist data in the host user's space
      #- /home/bwilab:/home/bwilab
    network_mode: host # use the host network
    privileged: true

# TODO map bwibot devices