version: "3"

services:
  bwi_system_s:
    runtime: nvidia
    image: bwi_system_i
    user: 1000:1000
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: bwi_system_c
    tty: true
    # this is set bc of errors with RViz being denied dbus comm w/ host
    security_opt:
      - apparmor:unconfined
    volumes: # volumes allow persistent data on the host
      - ./projects:/home/bwi-docker/projects
    # give the container access to the host's network
    network_mode: host
    # these usb device names are defined on the host using udev rules
    #devices:
      # - /dev/hokuyo:/dev/hokuyo
      # - /dev/segway_rmp:/dev/segway_rmp